name: drawing_on_demand
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^5.0.0
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.7
  google_sign_in: ^6.1.5
  pin_code_fields: ^8.0.1
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  sms_autofill: ^2.0.0
  dotted_border: ^2.1.0
  intl: ^0.18.0
  fluttertoast: ^8.0.8
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  is_first_run: ^1.0.0
  flutter_guid: ^0.3.1
dev_dependencies: 
  flutter_lints: ^2.0.3
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Plus Jakarta Sans
      fonts: 
        - asset: assets/fonts/PlusJakartaSansSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSansBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSansMedium.ttf
          weight: 500
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
