// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhjRDDpFXB_cBSNxuPjRoN_frrYRZE334',
    appId: '1:680472686977:web:af632211e99dcc9046b880',
    messagingSenderId: '680472686977',
    projectId: 'drawing-on-demand',
    authDomain: 'drawing-on-demand.firebaseapp.com',
    storageBucket: 'drawing-on-demand.appspot.com',
    measurementId: 'G-EESB90S8T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeVpMnAQBfqIZxX3035QH7wNJMm9ijQ-w',
    appId: '1:680472686977:android:ea38b74b4b6552f146b880',
    messagingSenderId: '680472686977',
    projectId: 'drawing-on-demand',
    storageBucket: 'drawing-on-demand.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB7Y9PE5HsENd4RRvwO5337HADHTPlNMk',
    appId: '1:680472686977:ios:0b589ae28a7a6c1d46b880',
    messagingSenderId: '680472686977',
    projectId: 'drawing-on-demand',
    storageBucket: 'drawing-on-demand.appspot.com',
    iosBundleId: 'com.example.drawingOnDemand',
  );
}
